name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.3.2
  provider: ^6.1.5+1
  go_router: ^17.0.0
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  qr_flutter: ^4.1.0
  mobile_scanner: ^7.1.3
  image_picker: ^1.2.1
  firebase_storage: ^13.0.4
  http: ^1.6.0
  file_saver: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
